import type { Category, Product, Review } from './types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-indoor',
    name: 'Indoor Plants',
    slug: 'indoor',
    icon: '',
    description: 'Air-purifying and lush green houseplants for your home and office.',
  },
  {
    id: 'cat-flowering',
    name: 'Flowering Plants',
    slug: 'flowering',
    icon: '🌸',
    description: 'Vibrant blossoms that add color, aroma, and life to balconies and gardens.',
  },
  {
    id: 'cat-succulents',
    name: 'Succulents & Cacti',
    slug: 'succulents',
    icon: '🌵',
    description: 'Drought-tolerant, low-maintenance beauties perfect for busy plant parents.',
  },
  {
    id: 'cat-herbs',
    name: 'Herbs & Kitchen',
    slug: 'herbs',
    icon: '🌿',
    description: 'Fresh aromatic herbs, tulsi, mint, and kitchen garden essentials.',
  },
  {
    id: 'cat-bonsai',
    name: 'Bonsai Trees',
    slug: 'bonsai',
    icon: '🌳',
    description: 'Artfully miniature tree sculptures that embody patience and zen elegance.',
  },
  {
    id: 'cat-pots',
    name: 'Pots & Planters',
    slug: 'pots-planters',
    icon: '🏺',
    description: 'Ceramic, terracotta, and biodegradable designer pots and hanging baskets.',
  },
  {
    id: 'cat-soil',
    name: 'Soil & Fertilizers',
    slug: 'soil-fertilizers',
    icon: '🪱',
    description: 'Organic potting mix, vermicompost, seaweed extract, and nutrient boosters.',
  },
  {
    id: 'cat-seeds',
    name: 'Seeds & Bulbs',
    slug: 'seeds',
    icon: '🌱',
    description: 'High germination flower, vegetable, and exotic plant seeds.',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-snake-plant',
    name: 'Sansevieria Snake Plant (Golden Hahnii)',
    slug: 'sansevieria-snake-plant',
    description:
      'The ultimate indestructible air-purifying plant recognized by NASA. Produces oxygen at night and removes toxins like formaldehyde and benzene. Perfect for bedrooms and corners with low light.',
    price: 249,
    mrp: 399,
    image_emoji: '🪴',
    image_url: null,
    category_id: 'cat-indoor',
    category: MOCK_CATEGORIES[0],
    rating: 4.9,
    review_count: 142,
    sunlight: 'Low',
    pet_safe: false,
    care_level: 'Easy',
    stock: 25,
    pot_sizes: ['Small (4")', 'Medium (6")', 'Large (8")'],
    water: 'Every 2-3 weeks',
    light: 'Low to bright indirect light',
    humidity: 'Normal room humidity',
    difficulty: 'Easy',
    is_trending: true,
    is_beginner_friendly: true,
    discount_percentage: 38,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-peace-lily',
    name: 'Peace Lily (Spathiphyllum)',
    slug: 'peace-lily',
    description:
      'Elegant dark green leaves with graceful white flower spathes. It visibly signals when thirsty by gently drooping, making it easy to care for.',
    price: 349,
    mrp: 499,
    image_emoji: '🌸',
    image_url: null,
    category_id: 'cat-flowering',
    category: MOCK_CATEGORIES[1],
    rating: 4.8,
    review_count: 98,
    sunlight: 'Low to Medium',
    pet_safe: false,
    care_level: 'Easy',
    stock: 18,
    pot_sizes: ['Medium (6")', 'Large (8")'],
    water: 'Once a week when top soil dries',
    light: 'Indirect medium sunlight',
    humidity: 'High (appreciates misting)',
    difficulty: 'Easy',
    is_trending: true,
    is_beginner_friendly: true,
    discount_percentage: 30,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-areca-palm',
    name: 'Areca Palm (Chrysalidocarpus)',
    slug: 'areca-palm',
    description:
      'Feathery arching fronds that bring tropical resort vibes into living spaces. Excellent natural humidifier and 100% pet-friendly.',
    price: 499,
    mrp: 799,
    image_emoji: '🌴',
    image_url: null,
    category_id: 'cat-indoor',
    category: MOCK_CATEGORIES[0],
    rating: 4.7,
    review_count: 85,
    sunlight: 'Medium',
    pet_safe: true,
    care_level: 'Medium',
    stock: 12,
    pot_sizes: ['Medium (6")', 'Large (10")', 'Extra Large (12")'],
    water: 'Twice a week in summer, weekly in winter',
    light: 'Bright filtered sunlight',
    humidity: 'Moderate to high',
    difficulty: 'Medium',
    is_trending: true,
    is_beginner_friendly: false,
    discount_percentage: 37,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-money-plant',
    name: 'Golden Pothos / Money Plant',
    slug: 'golden-pothos-money-plant',
    description:
      'Heart-shaped variegated green and yellow foliage. Believed in Vastu to bring prosperity, luck, and positive energy to homes.',
    price: 199,
    mrp: 299,
    image_emoji: '🌿',
    image_url: null,
    category_id: 'cat-indoor',
    category: MOCK_CATEGORIES[0],
    rating: 4.9,
    review_count: 210,
    sunlight: 'Low to Medium',
    pet_safe: false,
    care_level: 'Easy',
    stock: 40,
    pot_sizes: ['Small (4")', 'Medium (6") (Hanging)'],
    water: 'Once a week or grow directly in water',
    light: 'Tolerates low light up to bright indirect',
    humidity: 'Normal room humidity',
    difficulty: 'Easy',
    is_trending: false,
    is_beginner_friendly: true,
    discount_percentage: 33,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-jade-plant',
    name: 'Crassula Ovata Jade Plant (Good Luck Plant)',
    slug: 'jade-plant-crassula-ovata',
    description:
      'Fleshy oval jade-green leaves on miniature woody stems. Represents prosperity and friendship in Feng Shui. Thrives on minimal watering.',
    price: 269,
    mrp: 399,
    image_emoji: '🪴',
    image_url: null,
    category_id: 'cat-succulents',
    category: MOCK_CATEGORIES[2],
    rating: 4.8,
    review_count: 115,
    sunlight: 'High',
    pet_safe: false,
    care_level: 'Easy',
    stock: 30,
    pot_sizes: ['Small (4")', 'Medium (6")'],
    water: 'Once every 10-14 days',
    light: '4-6 hours direct or bright sunlight',
    humidity: 'Low dry air',
    difficulty: 'Easy',
    is_trending: true,
    is_beginner_friendly: true,
    discount_percentage: 32,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-spider-plant',
    name: 'Chlorophytum Spider Plant',
    slug: 'chlorophytum-spider-plant',
    description:
      'Ribbon-like striped leaves arching outward with baby spider plantlets. Completely non-toxic and 100% safe for cats and dogs.',
    price: 229,
    mrp: 349,
    image_emoji: '🌱',
    image_url: null,
    category_id: 'cat-indoor',
    category: MOCK_CATEGORIES[0],
    rating: 4.9,
    review_count: 73,
    sunlight: 'Medium',
    pet_safe: true,
    care_level: 'Easy',
    stock: 22,
    pot_sizes: ['Small (4")', 'Medium (6")'],
    water: 'Once a week',
    light: 'Medium indirect sunlight',
    humidity: 'Moderate',
    difficulty: 'Easy',
    is_trending: false,
    is_beginner_friendly: true,
    discount_percentage: 34,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-ficus-bonsai',
    name: 'Ficus Microcarpa Ginseng Bonsai',
    slug: 'ficus-ginseng-bonsai',
    description:
      'Exposed banyan-style aerial roots with a compact canopy of dark glossy green leaves. A living sculpture that brings peace and mindful zen.',
    price: 899,
    mrp: 1499,
    image_emoji: '🌳',
    image_url: null,
    category_id: 'cat-bonsai',
    category: MOCK_CATEGORIES[4],
    rating: 4.9,
    review_count: 64,
    sunlight: 'Medium',
    pet_safe: false,
    care_level: 'Medium',
    stock: 8,
    pot_sizes: ['Ceramic Oval Tray (8")'],
    water: 'When top inch feels dry',
    light: 'Bright indirect light',
    humidity: 'Moderate to high',
    difficulty: 'Medium',
    is_trending: true,
    is_beginner_friendly: false,
    discount_percentage: 40,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-boston-fern',
    name: 'Boston Fern (Nephrolepis Exaltata)',
    slug: 'boston-fern',
    description:
      'Lush cascading ruffled emerald fronds. Safe for curious cats and dogs, excellent for bathroom humidity or shady balconies.',
    price: 289,
    mrp: 449,
    image_emoji: '🌿',
    image_url: null,
    category_id: 'cat-indoor',
    category: MOCK_CATEGORIES[0],
    rating: 4.6,
    review_count: 48,
    sunlight: 'Low to Medium',
    pet_safe: true,
    care_level: 'Medium',
    stock: 14,
    pot_sizes: ['Medium (6") Hanging'],
    water: 'Keep soil lightly moist, mist often',
    light: 'Shady or dappled indirect light',
    humidity: 'High humidity',
    difficulty: 'Medium',
    is_trending: false,
    is_beginner_friendly: false,
    discount_percentage: 35,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-holy-tulsi',
    name: 'Krishna & Rama Tulsi Holy Basil',
    slug: 'krishna-rama-tulsi',
    description:
      'Sacred medicinal basil known for its divine fragrance, immune-boosting antioxidant tea, and spiritual presence in Indian courtyards.',
    price: 149,
    mrp: 249,
    image_emoji: '🌱',
    image_url: null,
    category_id: 'cat-herbs',
    category: MOCK_CATEGORIES[3],
    rating: 4.9,
    review_count: 320,
    sunlight: 'High',
    pet_safe: true,
    care_level: 'Easy',
    stock: 50,
    pot_sizes: ['Small (5")', 'Medium (7")'],
    water: 'Daily in morning',
    light: 'Direct sunshine (at least 4 hours)',
    humidity: 'Normal outdoor ambient',
    difficulty: 'Easy',
    is_trending: false,
    is_beginner_friendly: true,
    discount_percentage: 40,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-haworthia-zebra',
    name: 'Zebra Succulent (Haworthia Fasciata)',
    slug: 'zebra-succulent-haworthia',
    description:
      'Striking dark green rosettes with raised horizontal white pearl-like ridges. Compact desktop companion that needs watering only once a fortnight.',
    price: 189,
    mrp: 299,
    image_emoji: '🌵',
    image_url: null,
    category_id: 'cat-succulents',
    category: MOCK_CATEGORIES[2],
    rating: 4.8,
    review_count: 59,
    sunlight: 'Medium',
    pet_safe: true,
    care_level: 'Easy',
    stock: 35,
    pot_sizes: ['Mini (3.5")', 'Small (4.5")'],
    water: 'Once every 2 weeks',
    light: 'Bright indirect or morning sun',
    humidity: 'Low',
    difficulty: 'Easy',
    is_trending: false,
    is_beginner_friendly: true,
    discount_percentage: 36,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-adenium-desert-rose',
    name: 'Adenium Desert Rose (Bonsai Bloom)',
    slug: 'adenium-desert-rose',
    description:
      'Sculptural swollen succulent caudex base bearing spectacular trumpet-shaped bi-color crimson pink flowers.',
    price: 549,
    mrp: 899,
    image_emoji: '🌸',
    image_url: null,
    category_id: 'cat-flowering',
    category: MOCK_CATEGORIES[1],
    rating: 4.9,
    review_count: 82,
    sunlight: 'High',
    pet_safe: false,
    care_level: 'Medium',
    stock: 16,
    pot_sizes: ['Wide Clay Pot (7")'],
    water: 'Once a week, reduce in rainy season',
    light: 'Full direct sunlight',
    humidity: 'Low to moderate',
    difficulty: 'Medium',
    is_trending: true,
    is_beginner_friendly: false,
    discount_percentage: 38,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-monstera-deliciosa',
    name: 'Monstera Deliciosa (Swiss Cheese Plant)',
    slug: 'monstera-deliciosa',
    description:
      'Iconic split-leaf tropical foliage beloved worldwide. Fast-growing and instantly turns any interior into an urban jungle aesthetic.',
    price: 499,
    mrp: 799,
    image_emoji: '🪴',
    image_url: null,
    category_id: 'cat-indoor',
    category: MOCK_CATEGORIES[0],
    rating: 4.9,
    review_count: 178,
    sunlight: 'Medium',
    pet_safe: false,
    care_level: 'Easy',
    stock: 20,
    pot_sizes: ['Medium (6")', 'Large (8")', 'Extra Large (10") with Moss Pole'],
    water: 'Weekly when top 2 inches dry out',
    light: 'Bright indirect light',
    humidity: 'Moderate to high',
    difficulty: 'Easy',
    is_trending: true,
    is_beginner_friendly: true,
    discount_percentage: 37,
    seller_id: null,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-snake-plant',
    user_id: 'u-1',
    rating: 5,
    comment: 'Arrived in sturdy, eco-friendly corrugated packing. Not a single leaf was broken or bruised!',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    profiles: { name: 'Aarav Patel' },
  },
  {
    id: 'rev-2',
    product_id: 'prod-snake-plant',
    user_id: 'u-2',
    rating: 5,
    comment: 'Super healthy plant. Placed it right on my work desk, looking lush and vibrant.',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    profiles: { name: 'Sneha Deshmukh' },
  },
  {
    id: 'rev-3',
    product_id: 'prod-peace-lily',
    user_id: 'u-3',
    rating: 5,
    comment: 'Bloomed within 10 days of arrival. The AI advisor watering schedule guide was spot on.',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    profiles: { name: 'Divya Iyer' },
  },
];
